architect:
  - volodya-lombrozo
merge:
  script: echo "Hello rultor. Can you merge into main branch, please?"
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean test -P quality --file pom.xml --errors --batch-mode
